### ISSUE TITLE
How to re-login to Cursor account

### ISSUE THREAD

**Issue by Alecton4** [Helixform/CodeCursor#32]
I have logged in before, and it was working well several hours ago. I don't know why it's suddenly logged out, and I didn't find a way to re-login. I tried re-installing the extension but it does not work.

The log is as follows:

```log
[Extension Host] Error: Server returned status code 401
	at t.exports.__wbg_new_15d3966e9981a196 (/home/az/.vscode/extensions/ktiays.aicursor-0.4.0/dist/extension.js:1:10999)
	at wasm://wasm/000d775e:wasm-function[90]:0x79de
	at wasm://wasm/000d775e:wasm-function[99]:0xcb44
	at wasm://wasm/000d775e:wasm-function[153]:0x1a517
	at wasm://wasm/000d775e:wasm-function[394]:0x2ae06
	at I (/home/az/.vscode/extensions/ktiays.aicursor-0.4.0/dist/extension.js:1:3237)
	at o (/home/az/.vscode/extensions/ktiays.aicursor-0.4.0/dist/extension.js:1:2164)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by Alecton4** [comment]
Very strange that I only saw "Sign In / Sign Up" and "Generate Code" in the command panel. Now I can see "Sign Out".
